# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bec231f0cad825b9aa50aaa6676e4305e256283e48fa1c24ed6fca07116c5f6e42eefde6ab8094745e451a037451809934c88131e5083c9a4a156047f2beb427

test:
  secret_key_base: 1b65755e10560069db346ab843f90d4ad78ec74a07ff7881e39bb8c7324be64e846bd767befb1a719ad76664a8c4ec618aecd0683a077c35f4acc19b3e512944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
